package com.tamu.jo.business.am;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 22 16:41:39 CDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MaestroAMImpl
    extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MaestroAMImpl() {
    }

    /**
     * Container's getter for CountryVO1.
     * @return CountryVO1
     */
    public ViewObjectImpl getCountryVO1() {
        return (ViewObjectImpl)findViewObject("CountryVO1");
    }
}

